### ISSUE TITLE
Tooltip is showing at wrong place

### ISSUE THREAD

**Issue by ParitoshVaidya** [AndreiCalazans/rn-tooltip#7]
I added tooltip component as shown in read me.

I kept Text to right as well as left. Still, tooltip shows in the center.

```
<Tooltip popover={<Text>Info here</Text>} containerStyle={{width: 60, alignSelf: 'flex-end'}} withPointer={true}>
    <Text style={[{width: 60, alignSelf: 'flex-end'}]}>Press me</Text>
</Tooltip>
```

![screenshot_20180928-163223_cropped](https://user-images.githubusercontent.com/8125866/46204908-93cdeb00-c33c-11e8-9c14-a62c1943ae43.png)

**PS. Can you also send me link to example code?**

**Comment by AndreiCalazans** [comment]
Sorry for that, since the tooltip wraps a view around the element, it will lay itself out like a View and not like a Text. For you to accomplish what you want try the following

```
<View width={60} alignSelf='flex-end' >
    <Tooltip popover={<Text>Info here</Text>} withPointer={true}>
       <Text style={{ width: 60 }}>Press me</Text>
    </Tooltip> 
</View>
```

Note: I used props to style the view, however, you can use style prop.

<img width="282" alt="screen shot 2018-09-29 at 09 26 21" src="https://user-images.githubusercontent.com/20777666/46245781-06d17300-c3ca-11e8-833c-15518d1ad7c4.png">
